"""Shared presentation tokens for validation feedback and completion popups."""

from __future__ import annotations

from PySide6.QtGui import QColor

VALIDATION_LINE_BACKGROUND = QColor(255, 220, 220)
VALIDATION_COLUMN_ERROR_COLOR = QColor(220, 50, 50)
VALIDATION_LABEL_BACKGROUND = "#fdd"
VALIDATION_LABEL_FOREGROUND = "#900"

AUTOCOMPLETE_POPUP_MIN_WIDTH = 180
AUTOCOMPLETE_POPUP_MAX_HEIGHT = 160
AUTOCOMPLETE_POPUP_ROW_HEIGHT = 24
AUTOCOMPLETE_POPUP_VERTICAL_PADDING = 8
